Rewrote the makefile

diff --git a/src/lib/power/makefile b/src/lib/power/makefile
--- a/src/lib/power/makefile
+++ b/src/lib/power/makefile
@@ -1,2 +1,40 @@
-test:
-	gcc -o powerTest powerTest.c -lpower -lm
+CC = gcc
+SRC = libpower.c
+OBJFILE = libpower.o
+LIBDIR = lib
+LIBFILE = libpower.so
+TESTSRC = powerTest.c
+TESTFILE = powerTest
+
+# Build the test program
+test: $(LIBDIR)/$(LIBFILE)
+	@echo "\n\n*** Building test program $(TESTFILE) ***\n"
+	$(CC) -o $(TESTFILE) $(TESTSRC) -L./$(LIBDIR) -lpower -lm -Wl,-rpath,./$(LIBDIR)
+	@echo "*** Finished building test program! ***\n"
+
+# Build shared library
+$(LIBDIR)/$(LIBFILE): $(OBJFILE)
+	@echo "* Building libraries...\n"
+	@if ! [ -d $(LIBDIR) ]; \
+		then \
+		mkdir $(LIBDIR); \
+	fi
+	$(CC) -shared -fPIC -o $(LIBDIR)/$(LIBFILE) $(OBJFILE)
+	@echo "* Finished building libraries!\n"
+
+# Build object files
+$(OBJFILE): $(SRC)
+	@echo "* Building object files...\n"
+	$(CC) -I. -c $(SRC) -o $(OBJFILE)
+	@echo "* Finished building object files!\n"
+
+# Clean up everything generated by the make file
+clean:
+	@echo "\n*** Cleaning up files generated by make ***\n"
+	rm -f $(OBJFILE) $(TESTFILE)
+	@if [ -d $(LIBDIR) ]; \
+		then \
+		rm -f $(LIBDIR)/$(LIBFILE); \
+		rm -d $(LIBDIR); \
+	fi
+	@echo "\n*** Finished cleaning up ***\n"
